
name: "CI"
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    container: pipelinecomponents/hadolint:latest
    steps:
      - uses: actions/checkout@v1
      - name: Run hadolint
        run: hadolint Dockerfile

  build:
    runs-on: ubuntu-latest
    needs: ['lint']
    steps:
      - uses: actions/checkout@v1
      - name: Build Docker image
        run: docker build -t myimage:$GITHUB_SHA .

      - name: Save Docker image artifact
        run:  docker save -o semantic-release.tar semantic-release:$GITHUB_SHA

      - name: Upload image artifact
        uses: actions/upload-artifact@master
        with:
          name: semantic-release-image
          path: semantic-release.tar

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - name: Pull Image artifact
        uses: actions/download-artifact@master
        with:
          name: semantic-release-image

      - name: Load image into docker context
        run: docker load -i emantic-release-image/emantic-release-image.tar

      - name: Run Structure tests
        run:  docker run -i --rm -v /var/run/docker.sock:/var/run/docker.sock -v $PWD:/test zemanlx/container-structure-test:v1.8.0-alpine test --image semantic-release:$GITHUB_SHA --config test/structure-tests.yaml


